-- Select all customers
SELECT * FROM Customers;

-- Select all products
SELECT * FROM Products;

-- Select all suppliers
SELECT * FROM Suppliers;

-- Select all orders
SELECT * FROM Orders;

-- Select all order details
SELECT * FROM OrderDetails;

-- Select the name and country for each customer
SELECT CustomerName, Country FROM Customers;

-- Select the name of the product and its price
SELECT ProductName, Price FROM Products;

-- Select the names of suppliers that are in a specific country
SELECT SupplierName FROM Suppliers WHERE Country = 'Brasil';

-- Select orders made by a specific customer
SELECT * FROM Orders WHERE CustomerID = 1;

-- Select order details for a specific product
SELECT * FROM OrderDetails WHERE ProductID = 1;

-- Select product names and supplier names
SELECT p.ProductName, s.SupplierName
FROM Products p
JOIN Suppliers s ON p.SupplierID = s.SupplierID;

-- Select customer names and order dates
SELECT c.CustomerName, o.OrderDate
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID;

-- Select the total quantity ordered for each product
SELECT p.ProductName, SUM(od.Quantity) AS TotalQuantity
FROM OrderDetails od
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY p.ProductName;

-- Select the total number of orders placed by each customer
SELECT c.CustomerName, COUNT(o.OrderID) AS TotalOrders
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerName;

-- Select the total revenue generated by each product
SELECT p.ProductName, SUM(od.Quantity * p.Price) AS TotalRevenue
FROM OrderDetails od
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY p.ProductName;

-- Select orders that have a quantity greater than a specific value
SELECT * FROM OrderDetails WHERE Quantity > 1;

-- Select products that are priced within a specific range
SELECT * FROM Products WHERE Price BETWEEN 10 AND 30;

-- Select customers who are in a specific country sorted by name
SELECT * FROM Customers WHERE Country = 'Argentina' ORDER BY CustomerName;

-- Select products that contain a specific text string in their name
SELECT * FROM Products WHERE ProductName LIKE '%Leather%';

